-- Hourly ingestion is scheduled via the Supabase Dashboard, NOT from SQL.
--
-- Supabase's managed Postgres does not allow `alter database … set
-- app.settings.*` as the `postgres` role (error 42501), so the pg_cron
-- approach that works on self-hosted Postgres isn't available here.
-- Instead, use the Dashboard's built-in Cron feature — it handles auth
-- to the Edge Function automatically and stores the token outside SQL.
--
-- Setup, one time only:
--   1. Supabase Dashboard → Database → Cron Jobs → "Create a new cron job"
--   2. Name:      power10-ingest-hourly
--      Schedule: 5 * * * *
--      Type:     "Supabase Edge Function"
--      Function: ingest-articles
--      Method:   POST
--      Body:     {}
--   3. Save. The job begins running at the next matching minute.
--
-- This migration is intentionally a no-op so `supabase db push` still
-- succeeds cleanly. It exists only so future maintainers find this
-- comment when they wonder where the cron lives.

select 'Ingestion is scheduled via Supabase Dashboard → Database → Cron Jobs' as note;
